### ISSUE TITLE
Thanks for the invite?

### ISSUE THREAD

**Issue by VorpalBlade** [pskarin/wasp-poster#2]
Hi,

Sorry about this, but I did not see another way to contact you (such as email). I got an invite to join as collaborator on this repository from you. Before accepting I would like to know what you expect from me, and of the repository.

For example, I locally converted the QR codes for references to use the qrcode latex package (instead of eps files). I'm not sure that is a suitable change though (I don't know what LaTeX distributions include this package by default).

Which university are you affiliated with?

Best regards,
Arvid Norlander
PHD student, AASS, Örebro University

**Comment by pskarin** [comment]
Hi Arvid. I have no expectations, just wanted to empower you to make changes directly. I no longer use or make updates to this template myself. I am a WASP alumni from Lund but I am no longer directly affiliated with the university.

**Comment by VorpalBlade** [comment]
I thought I should let you know that I will no longer be associated with WASP as of the end of this month.
